import type { SkillEntry } from './types';

// Pre-fetched seed data from external sources.
// Each entry has enough info to display in the catalog without network access.

function seed(partial: Omit<SkillEntry, 'files' | 'hasScripts' | 'hasExamples' | 'fileCount'> & Partial<Pick<SkillEntry, 'files' | 'hasScripts' | 'hasExamples' | 'fileCount'>>): SkillEntry {
  return {
    files: [],
    hasScripts: false,
    hasExamples: false,
    fileCount: 1,
    ...partial,
  };
}

// ─── Anthropic Official Skills (anthropics/skills) ────────────────────────────

const anthropicBase = 'https://github.com/anthropics/skills/tree/main';
const anthropicSkills: SkillEntry[] = [
  seed({
    id: 'anthropic/skill-creator',
    name: 'skill-creator',
    description: 'Meta-skill that creates other Claude Code skills. Generates SKILL.md with proper frontmatter, folder structure, and supporting files.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/skill-creator`,
    level: 4,
    category: 'development',
    type: 'capability',
    coolness: 5,
    userInvocable: true,
    content: '# Skill Creator\n\nA meta-skill that helps you create new Claude Code skills with proper structure and frontmatter.',
  }),
  seed({
    id: 'anthropic/pdf',
    name: 'pdf',
    description: 'Generate PDF documents from markdown or structured data. Supports tables, charts, headers, and styled layouts.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/pdf`,
    level: 3,
    category: 'documentation',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# PDF Skill\n\nGenerate professional PDF documents from markdown content.',
  }),
  seed({
    id: 'anthropic/docx',
    name: 'docx',
    description: 'Generate Word documents (.docx) with formatting, tables, and styles.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/docx`,
    level: 3,
    category: 'documentation',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# DOCX Skill\n\nGenerate formatted Word documents.',
  }),
  seed({
    id: 'anthropic/pptx',
    name: 'pptx',
    description: 'Generate PowerPoint presentations with slides, layouts, and speaker notes.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/pptx`,
    level: 3,
    category: 'documentation',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# PPTX Skill\n\nGenerate PowerPoint presentations with structured slide content.',
  }),
  seed({
    id: 'anthropic/xlsx',
    name: 'xlsx',
    description: 'Generate Excel spreadsheets with formulas, charts, and multiple worksheets.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/xlsx`,
    level: 3,
    category: 'documentation',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# XLSX Skill\n\nGenerate Excel spreadsheets with data and formatting.',
  }),
  seed({
    id: 'anthropic/algorithmic-art',
    name: 'algorithmic-art',
    description: 'Generate algorithmic art using SVG, Canvas, or code-based visual patterns. Creates mathematical and generative art.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/algorithmic-art`,
    level: 3,
    category: 'design',
    type: 'capability',
    coolness: 5,
    userInvocable: true,
    content: '# Algorithmic Art\n\nGenerate beautiful algorithmic art using code-based visual patterns.',
  }),
  seed({
    id: 'anthropic/canvas-design',
    name: 'canvas-design',
    description: 'Create visual designs using HTML Canvas API. Diagrams, illustrations, and data visualizations.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/canvas-design`,
    level: 3,
    category: 'design',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# Canvas Design\n\nCreate visual designs and diagrams using HTML Canvas.',
  }),
  seed({
    id: 'anthropic/mcp-builder',
    name: 'mcp-builder',
    description: 'Build Model Context Protocol (MCP) servers and clients. Scaffolds tools, resources, and prompts.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/mcp-builder`,
    level: 4,
    category: 'development',
    type: 'capability',
    coolness: 5,
    userInvocable: true,
    content: '# MCP Builder\n\nBuild MCP servers with tools, resources, and prompts.',
  }),
  seed({
    id: 'anthropic/csv',
    name: 'csv',
    description: 'Parse and generate CSV files with proper escaping, headers, and data validation.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/csv`,
    level: 2,
    category: 'data',
    type: 'capability',
    coolness: 2,
    userInvocable: true,
    content: '# CSV Skill\n\nParse and generate CSV files.',
  }),
  seed({
    id: 'anthropic/html',
    name: 'html',
    description: 'Generate responsive HTML pages with inline styles. Single-file web pages and email templates.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/html`,
    level: 2,
    category: 'development',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# HTML Skill\n\nGenerate responsive HTML pages.',
  }),
  seed({
    id: 'anthropic/svg',
    name: 'svg',
    description: 'Generate SVG graphics — icons, diagrams, logos, and illustrations as scalable vector graphics.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/svg`,
    level: 2,
    category: 'design',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# SVG Skill\n\nGenerate scalable vector graphics for icons, diagrams, and illustrations.',
  }),
  seed({
    id: 'anthropic/mermaid',
    name: 'mermaid',
    description: 'Generate Mermaid diagrams — flowcharts, sequence diagrams, class diagrams, and more.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/mermaid`,
    level: 2,
    category: 'documentation',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# Mermaid Skill\n\nGenerate Mermaid diagrams for documentation and architecture visualization.',
  }),
  seed({
    id: 'anthropic/react-app',
    name: 'react-app',
    description: 'Scaffold and build React applications with modern patterns — hooks, context, routing, and component architecture.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/react-app`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# React App Skill\n\nBuild React applications with modern patterns.',
  }),
  seed({
    id: 'anthropic/nextjs-app',
    name: 'nextjs-app',
    description: 'Build Next.js applications with App Router, server components, API routes, and deployment configuration.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/nextjs-app`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# Next.js App Skill\n\nBuild Next.js applications with App Router and server components.',
  }),
  seed({
    id: 'anthropic/python-project',
    name: 'python-project',
    description: 'Set up Python projects with proper structure — pyproject.toml, virtual environments, testing, and type hints.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/python-project`,
    level: 2,
    category: 'development',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# Python Project Skill\n\nSet up Python projects with modern tooling.',
  }),
  seed({
    id: 'anthropic/go-project',
    name: 'go-project',
    description: 'Set up Go projects with proper module structure, testing, and idiomatic patterns.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/go-project`,
    level: 2,
    category: 'development',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# Go Project Skill\n\nSet up Go projects with idiomatic structure.',
  }),
  seed({
    id: 'anthropic/rust-project',
    name: 'rust-project',
    description: 'Set up Rust projects with Cargo, testing, error handling, and common crate patterns.',
    source: 'anthropic',
    sourceUrl: `${anthropicBase}/rust-project`,
    level: 2,
    category: 'development',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# Rust Project Skill\n\nSet up Rust projects with Cargo and idiomatic patterns.',
  }),
];

// ─── VoltAgent / awesome-agent-skills ─────────────────────────────────────────

const voltBase = 'https://github.com/VoltAgent/awesome-agent-skills/tree/main';
const voltSkills: SkillEntry[] = [
  seed({
    id: 'voltagent/vercel-nextjs',
    name: 'vercel-nextjs',
    description: 'Vercel Next.js deployment best practices — edge functions, ISR, middleware, and Vercel-specific optimizations.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/vercel-nextjs`,
    level: 3,
    category: 'devops',
    type: 'preference',
    coolness: 4,
    userInvocable: false,
    content: '# Vercel Next.js\n\nBest practices for deploying Next.js apps on Vercel.',
  }),
  seed({
    id: 'voltagent/stripe-integration',
    name: 'stripe-integration',
    description: 'Stripe payment integration — checkout sessions, webhooks, subscription billing, and PCI compliance patterns.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/stripe-integration`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 5,
    userInvocable: false,
    content: '# Stripe Integration\n\nIntegrate Stripe payments with checkout sessions and webhooks.',
  }),
  seed({
    id: 'voltagent/cloudflare-workers',
    name: 'cloudflare-workers',
    description: 'Cloudflare Workers development — edge computing, KV storage, Durable Objects, and R2 integration.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/cloudflare-workers`,
    level: 3,
    category: 'devops',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# Cloudflare Workers\n\nBuild edge applications with Cloudflare Workers.',
  }),
  seed({
    id: 'voltagent/supabase',
    name: 'supabase',
    description: 'Supabase integration — auth, real-time subscriptions, storage, edge functions, and Row Level Security.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/supabase`,
    level: 3,
    category: 'data',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# Supabase\n\nIntegrate with Supabase for auth, database, and real-time features.',
  }),
  seed({
    id: 'voltagent/trail-of-bits-security',
    name: 'trail-of-bits-security',
    description: 'Trail of Bits security audit patterns — vulnerability detection, smart contract analysis, binary analysis, and security best practices.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/trail-of-bits-security`,
    level: 4,
    category: 'security',
    type: 'capability',
    coolness: 5,
    userInvocable: false,
    content: '# Trail of Bits Security\n\nSecurity audit patterns from Trail of Bits.',
  }),
  seed({
    id: 'voltagent/anthropic-claude-api',
    name: 'anthropic-claude-api',
    description: 'Anthropic Claude API integration — messages API, tool use, streaming, vision, and prompt engineering patterns.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/anthropic-claude-api`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 5,
    userInvocable: false,
    content: '# Anthropic Claude API\n\nIntegrate with the Claude API for AI-powered features.',
  }),
  seed({
    id: 'voltagent/docker',
    name: 'docker',
    description: 'Docker containerization — Dockerfiles, multi-stage builds, compose files, and production optimization.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/docker`,
    level: 2,
    category: 'devops',
    type: 'capability',
    coolness: 3,
    userInvocable: false,
    content: '# Docker\n\nContainerize applications with optimized Dockerfiles.',
  }),
  seed({
    id: 'voltagent/github-actions',
    name: 'github-actions',
    description: 'GitHub Actions CI/CD — workflows, matrix builds, caching, deployment pipelines, and reusable actions.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/github-actions`,
    level: 3,
    category: 'devops',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# GitHub Actions\n\nBuild CI/CD pipelines with GitHub Actions.',
  }),
  seed({
    id: 'voltagent/tailwindcss',
    name: 'tailwindcss',
    description: 'Tailwind CSS best practices — utility-first patterns, custom themes, responsive design, and component styling.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/tailwindcss`,
    level: 2,
    category: 'design',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# Tailwind CSS\n\nBest practices for utility-first CSS with Tailwind.',
  }),
  seed({
    id: 'voltagent/prisma',
    name: 'prisma',
    description: 'Prisma ORM — schema design, migrations, queries, relations, and database optimization patterns.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/prisma`,
    level: 3,
    category: 'data',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# Prisma\n\nDatabase ORM with type-safe queries and migrations.',
  }),
  seed({
    id: 'voltagent/typescript-strict',
    name: 'typescript-strict',
    description: 'Strict TypeScript patterns — strict mode, branded types, exhaustive checks, and type-level programming.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/typescript-strict`,
    level: 2,
    category: 'development',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# TypeScript Strict\n\nStrict TypeScript patterns and type-level programming.',
  }),
  seed({
    id: 'voltagent/aws-lambda',
    name: 'aws-lambda',
    description: 'AWS Lambda development — handlers, layers, API Gateway integration, DynamoDB, and serverless patterns.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/aws-lambda`,
    level: 3,
    category: 'devops',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# AWS Lambda\n\nBuild serverless functions with AWS Lambda.',
  }),
  seed({
    id: 'voltagent/graphql',
    name: 'graphql',
    description: 'GraphQL API development — schema design, resolvers, subscriptions, and client integration with Apollo/urql.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/graphql`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# GraphQL\n\nBuild GraphQL APIs with schema-first design.',
  }),
  seed({
    id: 'voltagent/redis',
    name: 'redis',
    description: 'Redis patterns — caching, pub/sub, rate limiting, session storage, and data structure best practices.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/redis`,
    level: 2,
    category: 'data',
    type: 'capability',
    coolness: 3,
    userInvocable: false,
    content: '# Redis\n\nRedis caching, pub/sub, and data structure patterns.',
  }),
  seed({
    id: 'voltagent/testing-best-practices',
    name: 'testing-best-practices',
    description: 'Testing best practices — unit, integration, e2e testing patterns, mocking strategies, and test architecture.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/testing-best-practices`,
    level: 2,
    category: 'testing',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# Testing Best Practices\n\nComprehensive testing patterns across unit, integration, and e2e.',
  }),
  seed({
    id: 'voltagent/openai-api',
    name: 'openai-api',
    description: 'OpenAI API integration — chat completions, function calling, embeddings, assistants API, and streaming.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/openai-api`,
    level: 3,
    category: 'development',
    type: 'capability',
    coolness: 4,
    userInvocable: false,
    content: '# OpenAI API\n\nIntegrate with OpenAI APIs for AI-powered features.',
  }),
  seed({
    id: 'voltagent/postgres',
    name: 'postgres',
    description: 'PostgreSQL — schema design, migrations, indexing, query optimization, and connection pooling.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/postgres`,
    level: 2,
    category: 'data',
    type: 'capability',
    coolness: 3,
    userInvocable: false,
    content: '# PostgreSQL\n\nPostgreSQL database design and optimization patterns.',
  }),
  seed({
    id: 'voltagent/auth-patterns',
    name: 'auth-patterns',
    description: 'Authentication patterns — JWT, OAuth 2.0, session management, RBAC, and secure auth flows.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/auth-patterns`,
    level: 3,
    category: 'security',
    type: 'preference',
    coolness: 4,
    userInvocable: false,
    content: '# Auth Patterns\n\nSecure authentication and authorization patterns.',
  }),
  seed({
    id: 'voltagent/figma-to-code',
    name: 'figma-to-code',
    description: 'Convert Figma designs to production code — component extraction, responsive layouts, and design token mapping.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/figma-to-code`,
    level: 4,
    category: 'design',
    type: 'capability',
    coolness: 5,
    userInvocable: false,
    content: '# Figma to Code\n\nConvert Figma designs to production-ready code.',
  }),
  seed({
    id: 'voltagent/error-handling',
    name: 'error-handling',
    description: 'Error handling patterns — structured errors, error boundaries, retry logic, and graceful degradation.',
    source: 'voltagent',
    sourceUrl: `${voltBase}/error-handling`,
    level: 2,
    category: 'quality',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# Error Handling\n\nStructured error handling and graceful degradation patterns.',
  }),
];

// ─── Community / awesome-claude-code ──────────────────────────────────────────

const communitySkills: SkillEntry[] = [
  seed({
    id: 'community/git-conventional-commits',
    name: 'git-conventional-commits',
    description: 'Enforce conventional commit messages — feat, fix, chore, docs prefixes with scope and breaking change notation.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 1,
    category: 'quality',
    type: 'preference',
    coolness: 2,
    userInvocable: false,
    content: '# Git Conventional Commits\n\nEnforce conventional commit message format.',
  }),
  seed({
    id: 'community/code-review-checklist',
    name: 'code-review-checklist',
    description: 'Comprehensive code review checklist — readability, performance, security, testing, and documentation checks.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 2,
    category: 'quality',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# Code Review Checklist\n\nComprehensive checklist for thorough code reviews.',
  }),
  seed({
    id: 'community/readme-generator',
    name: 'readme-generator',
    description: 'Generate comprehensive README files from project structure — badges, installation, usage, API docs, and contributing guides.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 2,
    category: 'documentation',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# README Generator\n\nGenerate comprehensive README files from project analysis.',
  }),
  seed({
    id: 'community/api-design',
    name: 'api-design',
    description: 'REST API design standards — resource naming, versioning, pagination, error responses, and OpenAPI spec generation.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 2,
    category: 'development',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# API Design\n\nREST API design standards and OpenAPI generation.',
  }),
  seed({
    id: 'community/performance-audit',
    name: 'performance-audit',
    description: 'Web performance audit — Core Web Vitals, bundle size analysis, lazy loading, caching strategies, and Lighthouse optimization.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 3,
    category: 'quality',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# Performance Audit\n\nAudit web performance and optimize Core Web Vitals.',
  }),
  seed({
    id: 'community/accessibility-checker',
    name: 'accessibility-checker',
    description: 'Accessibility audit — WCAG 2.1 compliance, ARIA attributes, color contrast, keyboard navigation, and screen reader testing.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 3,
    category: 'quality',
    type: 'capability',
    coolness: 4,
    userInvocable: true,
    content: '# Accessibility Checker\n\nAudit and fix WCAG 2.1 accessibility issues.',
  }),
  seed({
    id: 'community/monorepo-nx',
    name: 'monorepo-nx',
    description: 'Nx monorepo patterns — workspace configuration, project graph, task caching, and affected command optimization.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 3,
    category: 'architecture',
    type: 'preference',
    coolness: 3,
    userInvocable: false,
    content: '# Monorepo Nx\n\nNx monorepo configuration and optimization patterns.',
  }),
  seed({
    id: 'community/database-migration',
    name: 'database-migration',
    description: 'Database migration patterns — zero-downtime migrations, rollback strategies, data backfill, and schema versioning.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 3,
    category: 'data',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# Database Migration\n\nZero-downtime database migration patterns.',
  }),
  seed({
    id: 'community/prompt-engineering',
    name: 'prompt-engineering',
    description: 'Prompt engineering patterns — chain-of-thought, few-shot examples, system prompts, and structured output formatting.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 2,
    category: 'development',
    type: 'preference',
    coolness: 4,
    userInvocable: false,
    content: '# Prompt Engineering\n\nPatterns for effective AI prompt engineering.',
  }),
  seed({
    id: 'community/dependency-update',
    name: 'dependency-update',
    description: 'Automated dependency updates — version analysis, breaking change detection, and safe upgrade strategies.',
    source: 'community',
    sourceUrl: 'https://github.com/hesreallyhim/awesome-claude-code',
    level: 2,
    category: 'devops',
    type: 'capability',
    coolness: 3,
    userInvocable: true,
    content: '# Dependency Update\n\nSafe automated dependency upgrade strategies.',
  }),
];

export const seedSkills: SkillEntry[] = [
  ...anthropicSkills,
  ...voltSkills,
  ...communitySkills,
];
